services:
  - type: web
    name: fvs-novo-site
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 18.17.0
    maxInstanceCount: 1
    minInstanceCount: 1
